### PR TITLE
Decoupling from django-node

### PR DESCRIPTION
**Pull request by mic159**
I'v been playing around with your library for a bit and had some suggestions.

I was considering how this would run in production, and dont think it should automatically start the node service and run npm install during the request-response cycle of the django app.
Ideally the service would be run and monitored from the service manager you are using (eg. supervisord), and if it isn't there it will error.

I also think it would be better to have the node service as part of the nodejs dependencies of your project, not have it installed in python's site-packages.
I do see what your trying to achieve with django-node and service-host, but it does add some  complexity.

I've forked django-react and simplified it along these lines.
Would something like this be something you would want to take upstream?

### CODE REVIEW

**Comment by markfinger** [comment]
I'll take a look at the PR when I've got some time. But re: production...

We're using supervisor to run the management command `start_node_server`, so when the python process boots it'll connect to a more stable process. The command's bundled with the django-node package.

You can run another command, `install_package_dependencies`, to install all the dependencies. Generally though we've just left it to runtime resolution though. It's a bit shit, but I've struggled to find a better way to do it that doesn't involve a bunch of steps to setup an env.

**Comment by markfinger** [comment]
Hmm, just musing over this for a bit and I think you've made some really good points. Will do a bit of a brain dump when I've some time...

**Comment by markfinger** [comment]
I think the gist of what you're advocating is both valid and inline with what I've been trying to do. The JS parts of the projects are handling most of the complexity and I've been slowly making progress such that the python bindings do little more than configure the processes.

I think you've simplified the service a lot - which is great - but if you look through the commit history, you'll see that you've mostly reverted changes related to detecting changes in related source. Most of the complexity in the service grew out of the need to invalidate node's cache whenever a component or one of its dependencies changed. The overhead of using webpack for circumventing the cache is crap, but I've yet to find any alternatives besides restarting the process or rolling your own cache invalidator (which would need to walk the dependency trees and clear node's module cache).

I suppose you could optimise for component rendering workflows by watching the source files with `nodemon`, or somesuch, and restarting the process whenever your source files change, but that'll continually clear the caches used by other services. Webpack, for example, is stupidly slow on the first build, but successive builds on watched source are quite performant.

Shifting the server within the service also makes it difficult to integrate it into other hosts, or to use it in a programmatic fashion. The flexibility of either approach is what I've been laying the groundwork for with the service host.

I gather that you're use case is mostly rendering components, but to provide context we've got a couple of projects running various js services - webpack/react/less/autoprefixer/cleancss/uglify/etc - which are all slow on a cold boot, but are performant once you've got some warm caches.

In any case, the long-term plan is to deprecate django-react, replacing it with some low-level python bindings. Mindful of that, I've dumped the service codebase over at https://github.com/markfinger/react-rendering-service and made a couple of small tweaks. You're more than welcome to make the PR there and we can continue sorting things out.

Cheers,
Mark

**Comment by mic159** [comment]
To watch for changes, I changed it to just use fs.watch and deleted the require cache.
My idea is that the user's project should only be supplying a compiled pack to the render service, not a JSX file.

People are going to have to compile it down to JS using a builder for the client side anyway, so they should also create a pack for the server render too.
In my case I'm use Webpack to package the client side, so I have a webpack.config.client.js targeting "web" and a webpack.config.server.js targeting "node".
This means the user is in full control over the libraries and code that goes in, including how its compiled, and the server does not have to follow any dependencies or do any compilation itself.

I think it follows the ideal situation for production too, where everything is pre-compiled as part of your deployment process.

**Comment by markfinger** [comment]
I think your approach is better, simpler, and cleaner - and it was what I had originally built and used myself - but in practice I've found it introduces more problems than it solves once you have a team of people trying to build atop it. Generating your own bundles for server-side use is fine in principle and may work well in many situations, but I've found that it introduced inconsistent behaviour and duplicating the bundle configs produces more maintenance overheads. 

If the rendered output reflects the ambiguous state of an async watch process which has watch delays & build times, you introduce the problem that the rendered markup may or may not match the output produced in a second or two. We had folks sitting there refreshing a page multiple times waiting to see if that would fix the problem. That ambiguity of using a background process is both frustrating and avoidable. Blocking during the build process solves the issue of inconsistent output, but detecting an external process's build state is a total nightmare involving even more overhead. Hence why the server-side bundle generation is packaged in to the service.

With regards to production, the watchers are turned off and it simply requires the components via babel. Other than avoiding the initial overhead of the translator, I'm not sure if there are many benefits for pre-compiling the components for server-side use.

You're more than welcome to make a PR adding a flag which triggers a watch of the file itself. This would allow more flexibility by avoiding the bundling process.

**Comment by mic159** [comment]
Turns out that you dont need multiple webpack config files!
You can just return an array of objects in your webpack.config.js file.
```javascript
module.exports = [{
  ... client side ...
}, {
  ... server side ...
}];
```
And its just javascript, so you can set defaults and override only whats needed for the server side.

This means you only need one `webpack --watch` after all!

**Comment by markfinger** [comment]
Cool, that's good to know

**Pull request closed without merging**
